# GitHub action to verify `clarinet check` runs against contract
# Uses a prepare script outlined in testing section of README

name: CI Clarinet

# Controls when the action will run.
on:
  push:

concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    name: check - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true      
      - name: "Check contract"
        uses: docker://hirosystems/clarinet:1.7.1
        with:
          entrypoint: "bash"
          args: -c "clarinet check"
  test:
    name: test - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true      
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:1.7.1
        with:  
          entrypoint: "bash"
          args: -c "clarinet test --coverage"
